### ISSUE TITLE
Migrate to layer5io?

### ISSUE THREAD

**Issue by leecalcote** [layer5io/chart-releaser-action#1]
Hi @Aisuko,

If we can avoid external dependencies one on this releaser action, we try to do so. Would you like to transfer this repo to `layer5io`?

- Lee

**Comment by Aisuko** [comment]
@leecalcote Of course, sir.

**Comment by leecalcote** [comment]
Excellent. Thank you, @Aisuko. I will look to see if we can apply the layer5-repo-template retroactively to this repo.
